export {
  FLOWER_TILE_KINDS,
  FOUR_COPY_FLOWER_KINDS,
  FOUR_COPY_INDEXES,
  GAME_CORE_MODULE,
  NUMBER_TILE_RANKS,
  NUMBER_TILE_SUITS,
  PLANT_FLOWER_KINDS,
  SEASON_FLOWER_KINDS,
  WIND_TILE_KINDS,
} from './state';
export type {
  DrawTileFromWallResult,
  DrawnTileResolutionResult,
  FlowerReplacementResult,
  FlowerKongKind,
  FlowerTile,
  FlowerTileId,
  FlowerTileKind,
  FourCopyFlowerTile,
  FourCopyFlowerTileId,
  FourCopyFlowerKind,
  FourCopyIndex,
  GamePhase,
  GameState,
  HandProgressFacts,
  HandResult,
  DrawHandResult,
  WinHandResult,
  WinHandWinner,
  HuEvaluation,
  HuPattern,
  HuSource,
  MahjongTile,
  NumberTile,
  NumberTileId,
  NumberTileRank,
  NumberTileSuit,
  OrdinaryHandTile,
  OrdinaryTileFace,
  PlantFlowerTile,
  PlantFlowerTileId,
  PendingAction,
  PendingActionType,
  PendingAnGangScoringEvent,
  PendingBuGangIntent,
  PendingBuGangScoringEvent,
  PendingFlowerKongScoringEvent,
  PendingMingGangScoringEvent,
  PendingHuScoringEvent,
  PendingScoringEvent,
  LastDiscard,
  PlantFlowerKind,
  ReactionAvailability,
  ReactionResponder,
  ReactionResponse,
  ReactionWindow,
  ReactionWindowBase,
  DiscardReactionWindow,
  BuGangReactionWindow,
  ReactionWindowStatus,
  ScoringEventCreationStage,
  ScoreTransfer,
  SeasonFlowerTile,
  SeasonFlowerTileId,
  SeasonFlowerKind,
  SinglePlayerFlowerReplacementInput,
  SinglePlayerFlowerReplacementResult,
  Tile,
  TileId,
  TileWall,
  TurnStage,
  Wall,
  WindTile,
  WindTileId,
  WindTileKind,
} from './state';

export {
  DEFAULT_RULE_SET_ID,
  NANJING_OPEN_RULE_SET,
  RULE_SET_REGISTRY,
  getRuleSet,
  listRuleSets,
} from './rules';
export type {
  AnGangScoringContext,
  BuGangScoringContext,
  FlowerKongScoringContext,
  HuEvaluationContext,
  HuScoringContext,
  MingGangScoringContext,
  RuleSet,
  RuleSetId,
} from './rules';

export { SEATS, createInitialPlayers } from './player';
export type { BuGangDrawProvenance, DiscardRecord, PlayerState, Seat } from './player';
export type { Meld, MeldType } from './meld';

export type {
  ClaimReactionAction,
  DeclareAnGangAction,
  DeclareBuGangAction,
  DiscardAction,
  DrawAction,
  GameAction,
  PassReactionAction,
  ReactionAction,
  ReactionResponseType,
  ResolveReactionWindowAction,
  SubmitReactionAction,
  StartGameAction,
} from './actions';
export type { GameCreationOptions, RuleSetOptions, StartGameOptions } from './options';

export {
  createNanjingMahjongDeck,
  createNanjingMahjongTileWall,
  createTileWall,
  drawTileFromWallHead,
  drawTileFromWallTail,
  getAvailableAnGangs,
  getAvailableBuGangs,
  isFlowerTile,
  isNumberTile,
  isOrdinaryHandTile,
  isWindTile,
  replaceFlowersForSinglePlayer,
  requiresFlowerReveal,
  resolveDrawnTileWithFlowerReplacement,
} from './reducer';
export type { AvailableBuGang } from './reducer';

export { evaluateHuStructure, ordinaryTileFace, ordinaryTileFaceKey } from './hu';
export type {
  DragonSevenPairsHuStructure,
  HuConcealedMeld,
  HuSequence,
  HuStructure,
  HuStructureInput,
  HuTriplet,
  SevenPairsHuStructure,
  StandardHuStructure,
} from './hu';

export {
  advanceTurn,
  applyAction,
  createGame,
  createInitialGame,
  gameEngine,
  startGame,
} from './engine';
export type { GameEngine } from './engine';

export {
  applyGameActionToMatch,
  completeCurrentHand,
  createInitialHandForMatch,
  createMatch,
  prepareNextHand,
  settlePendingScoringEvents,
  startCurrentHand,
  startMatch,
} from './match';
export type {
  CompletedHandResult,
  DealerTransition,
  CompletedHandSummary,
  CreateInitialHandForMatchOptions,
  HandCompletion,
  HandCompletionReason,
  HandStatus,
  MatchCreationOptions,
  MatchState,
  MatchStatus,
  StartMatchOptions,
} from './match';
